### ISSUE TITLE
"Make online" no longer works

### ISSUE THREAD

**Issue by yorkfrog** [shivareddyiirs/QRealTime#51] opened 2020-06-01 15:29 UTC
**Describe the bug**
I use 'make online' option to create form online and it generates a python error.  This did work after the update 3.13 but seems to have stopped working after past week.  

Goto View-->Panels-->Log Message
Stacktrace: 
```
An error has occurred while executing Python code: 

KeyError: 'uid' 
Traceback (most recent call last):
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 286, in sendForm
    service.prepareSendForm(layer)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 640, in prepareSendForm
    self.sendForm(layer.name(),payload)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 668, in sendForm
    urlDeploy = self.getValue('url')+"/assets/"+responseJson['uid']+"/deployment/"
KeyError: 'uid'


Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c 

Python Path:
/usr/share/qgis/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/colin/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime
/home/colin/proj/qgis-test/relations
```

QRT messages

```
2020-06-01T16:24:35     INFO    not writing fieldsNone
2020-06-01T16:24:35     INFO    'type'None
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    getFieldModelExternalResource
2020-06-01T16:24:35     INFO    got an image type fieldNone
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    getFieldModelTextEdit
2020-06-01T16:24:35     INFO    fieldDict[{'type': 'geopoint', 'required': True, 'label': 'Point Location'}, {'name': 'tag_no', 'label': 'tag_no', 'type': 'integer'}, {'name': 'tree_no', 'label': 'tree_no', 'type': 'integer'}, {'name': 'species', 'label': 'species', 'type': 'text'}, {'name': 'notes', 'label': 'notes', 'type': 'text'}, {'name': 'photo', 'label': 'Photo', 'type': 'image'}, {'name': 'testInt', 'label': 'testInt', 'type': 'integer'}, {'name': 'testTxt', 'label': 'testTxt', 'type': 'text'}]
2020-06-01T16:24:35     INFO    Payload= {'uid': 'tree-loc-layer', 'name': 'tree-loc-layer', 'asset_type': 'survey', 'content': '{"survey": [{"type": "geopoint", "required": true, "label": "Point Location"}, {"name": "tag_no", "label": "tag_no", "type": "integer"}, {"name": "tree_no", "label": "tree_no", "type": "integer"}, {"name": "species", "label": "species", "type": "text"}, {"name": "notes", "label": "notes", "type": "text"}, {"name": "photo", "label": "Photo", "type": "image"}, {"name": "testInt", "label": "testInt", "type": "integer"}, {"name": "testTxt", "label": "testTxt", "type": "text"}], "choices": []}'}
```

**To Reproduce**
Open project
goto layer to create online
from QRT menu, "make online"
See error
Check Kobo toolbox and see no form was created

**Expected behavior**
Create online like it used to.

please complete the following information):
 - OS: Ubuntu 18.04
 - QGIS Version 3.6.3
 - Plugin Version 3.13

**Additional context**
This used to work after 3.13 update, so I wonder if there has been some change to the Kobo API.
I can still import records from other layers that already have forms on Kobo
I did delete and reinstall the plugin but this made no difference.

**Comment by shivareddyiirs** [comment] 2020-06-04 09:57
This issue is closed in new version 3.14

**Closed as completed by shivareddyiirs** 2020-06-04 09:57 UTC
Labels: bug

**Comment by yorkfrog** [comment] 2020-06-05 17:05
Hi - I installed v3.14 and still have the problem.
One extra bit of info 
- I tried to 'make online' a layer that already had a form in Kobo and it worked ok - although there weren't any changes.
- I then deleted that form from Kobo.  
- Then tried to 'make online' again but this time it failed in the same way as in the main bug with the `KeyError: 'uid'` 

The stacktrace and QRT message log are below.

```
Traceback (most recent call last):
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 286, in sendForm
    service.prepareSendForm(layer)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 643, in prepareSendForm
    self.sendForm(layer.name(),payload)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 670, in sendForm
    urlDeploy = self.getValue('url')+"assets/"+responseJson['uid']+"/deployment/"
KeyError: 'uid'


Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c 

Python Path:
/usr/share/qgis/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/colin/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime
/home/colin/proj/qgis-test/relations
```

```
2020-06-05T18:00:35     INFO    not writing fieldsNone
2020-06-05T18:00:35     INFO    'type'None
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelExternalResource
2020-06-05T18:00:35     INFO    got an image type fieldNone
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelExternalResource
2020-06-05T18:00:35     INFO    got an image type fieldNone
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    fieldDict[{'type': 'geopoint', 'required': True, 'label': 'Point Location'}, {'name': 'id', 'label': 'id', 'type': 'integer'}, {'name': 'text1', 'label': 'text1', 'type': 'text'}, {'name': 'int1', 'label': 'int1', 'type': 'integer'}, {'name': 'decimal1', 'label': 'decimal1', 'type': 'decimal'}, {'name': 'image1', 'label': 'image1', 'type': 'image'}, {'name': 'text2', 'label': 'text2', 'type': 'text'}, {'name': 'int2', 'label': 'int2', 'type': 'integer'}, {'name': 'decimal2', 'label': 'decimal2', 'type': 'decimal'}, {'name': 'image2', 'label': 'image2', 'type': 'image'}, {'name': 'text3', 'label': 'text3', 'type': 'text'}, {'name': '__version_', 'label': '__version_', 'type': 'text'}]
2020-06-05T18:00:35     INFO    Payload= {'uid': 'test-qrt-to-kobo-export', 'name': 'test-qrt-to-kobo-export', 'asset_type': 'survey', 'content': '{"survey": [{"type": "geopoint", "required": true, "label": "Point Location"}, {"name": "id", "label": "id", "type": "integer"}, {"name": "text1", "label": "text1", "type": "text"}, {"name": "int1", "label": "int1", "type": "integer"}, {"name": "decimal1", "label": "decimal1", "type": "decimal"}, {"name": "image1", "label": "image1", "type": "image"}, {"name": "text2", "label": "text2", "type": "text"}, {"name": "int2", "label": "int2", "type": "integer"}, {"name": "decimal2", "label": "decimal2", "type": "decimal"}, {"name": "image2", "label": "image2", "type": "image"}, {"name": "text3", "label": "text3", "type": "text"}, {"name": "__version_", "label": "__version_", "type": "text"}], "choices": []}'}
```
thanks. Colin

**Comment by shivareddyiirs** [comment] 2020-06-06 15:58
Hey I am not able to reproduce this error , I am using humanitarian instance of kobo.

**Comment by yorkfrog** [comment] 2020-06-19 11:34
Hi - I installed v3.14 and still have the problem.
One extra bit of info 
- I tried to 'make online' a layer that already had a form in Kobo and it worked ok - although there weren't any changes.
- I then deleted that form from Kobo.  
- Then tried to 'make online' again but this time it failed in the same way as in the main bug with the `KeyError: 'uid'` 

The stacktrace and QRT message log are below.

```
Traceback (most recent call last):
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 286, in sendForm
    service.prepareSendForm(layer)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 643, in prepareSendForm
    self.sendForm(layer.name(),payload)
  File "/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime_dialog.py", line 670, in sendForm
    urlDeploy = self.getValue('url')+"assets/"+responseJson['uid']+"/deployment/"
KeyError: 'uid'


Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c 

Python Path:
/usr/share/qgis/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/colin/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python
/home/colin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime
/home/colin/proj/qgis-test/relations
```

```
2020-06-05T18:00:35     INFO    not writing fieldsNone
2020-06-05T18:00:35     INFO    'type'None
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelExternalResource
2020-06-05T18:00:35     INFO    got an image type fieldNone
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelExternalResource
2020-06-05T18:00:35     INFO    got an image type fieldNone
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    getFieldModelTextEdit
2020-06-05T18:00:35     INFO    fieldDict[{'type': 'geopoint', 'required': True, 'label': 'Point Location'}, {'name': 'id', 'label': 'id', 'type': 'integer'}, {'name': 'text1', 'label': 'text1', 'type': 'text'}, {'name': 'int1', 'label': 'int1', 'type': 'integer'}, {'name': 'decimal1', 'label': 'decimal1', 'type': 'decimal'}, {'name': 'image1', 'label': 'image1', 'type': 'image'}, {'name': 'text2', 'label': 'text2', 'type': 'text'}, {'name': 'int2', 'label': 'int2', 'type': 'integer'}, {'name': 'decimal2', 'label': 'decimal2', 'type': 'decimal'}, {'name': 'image2', 'label': 'image2', 'type': 'image'}, {'name': 'text3', 'label': 'text3', 'type': 'text'}, {'name': '__version_', 'label': '__version_', 'type': 'text'}]
2020-06-05T18:00:35     INFO    Payload= {'uid': 'test-qrt-to-kobo-export', 'name': 'test-qrt-to-kobo-export', 'asset_type': 'survey', 'content': '{"survey": [{"type": "geopoint", "required": true, "label": "Point Location"}, {"name": "id", "label": "id", "type": "integer"}, {"name": "text1", "label": "text1", "type": "text"}, {"name": "int1", "label": "int1", "type": "integer"}, {"name": "decimal1", "label": "decimal1", "type": "decimal"}, {"name": "image1", "label": "image1", "type": "image"}, {"name": "text2", "label": "text2", "type": "text"}, {"name": "int2", "label": "int2", "type": "integer"}, {"name": "decimal2", "label": "decimal2", "type": "decimal"}, {"name": "image2", "label": "image2", "type": "image"}, {"name": "text3", "label": "text3", "type": "text"}, {"name": "__version_", "label": "__version_", "type": "text"}], "choices": []}'}
```
thanks. Colin

**Comment by yorkfrog** [comment] 2020-06-19 11:40
Hi.  I have been digging further with this.  I went back to the last version of QRT that I think worked - 3.12.  I reinstalled that and found that it fails with the same error.  I have also tried against 3.15 and see same error.

I also created a new KF account to see if I had messed anything up on the server side but got the same error.

This seems like an API data error.  I looked up the Kobo release notes and see that the latest version has been deployed to the KF but not to the humanitarian instance yet.  But to be fair, the timings on that release don't right for this error.  [https://community.kobotoolbox.org/tag/release-notes]

I'm going to try to create an account on the humanitarian instance and see if I can reproduce there.  Alternatively, I am happy to give you access to my KF account if you want to test against that.

-C

**Comment by yorkfrog** [comment] 2020-06-19 11:52
Hi.  I signed up for an account on kobo.humanitarianresponse.info.  I connected QRT to it and tested with the same layer as failed earlier.  It Worked!!!!

So there is definitely a difference between the REST API on KF and the UNHCR instance.  I'll dig around and see if I can find concrete data examples.
-C

**Comment by yorkfrog** [comment] 2020-06-19 12:33
OK.  So I switch back to KF instance to test - and it works!  The joy's of distributed computing.  I have tested the same layers/forms that failed this morning and they now work.  

So I suspect something has changed on the KF instance, but I can't rule out some weirdness in-between client/server or in my own environment.

So I guess I'm happy but I don't like it when magic happens!
-C

**Comment by shivareddyiirs** [comment] 2020-06-19 15:27
I guess it may be cache
